version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  openfaas:
    lang: golang-middleware
    handler: ./users/transport/openfaas
    image: marceloaguero/serverless-api:latest
