version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  openfaas:
    lang: golang-middleware
    handler: ./users/transport/openfaas
    image: marceloaguero/serverless-api:latest
    build_args:
      GO111MODULE: on
    environment:
      DB_DSN: serverless:supersecret@tcp(mysql.db.svc.cluster.local:3306)
      DB_NAME: serverless
      TABLE_NAME: users
